const User = require("../models/User");
const bcrypt = require("bcryptjs");
const sendToken = require("../utils/sendToken");
const { v4: uuidv4 } = require("uuid");
const generateSupportId = require("../utils/generateSupportId");
const Professional = require("../models/Professional");

// ✅ REGISTER
exports.register = async (req, res) => {
  try {
    const { email, password, name, picture, role, phone } = req.body;

    // 1️⃣ Check existing user
    const exists = await User.findOne({ email });

    if (exists) {
      return res.status(400).json({
        detail: "Email already registered",
      });
    }

    // 2️⃣ Hash password
    const hash = await bcrypt.hash(password, 10);

    // 3️⃣ Create user
    // ❗ cust_id is auto-generated by schema middleware
    const user_id = `user_${uuidv4().replace(/-/g, "").slice(0, 12)}`;
    const support_id = await generateSupportId(role);
    const user = await User.create({
      user_id,
      support_id,
      email,
      password_hash: hash,
      name,
      picture,
      role, // optional (you may want to restrict this)
      phone,
    });

    if (role === "professional") {
      await Professional.create({
        user_id: user.user_id,
        service_categories: [],
        availability: {},
        verified: false,

        // metrics (system controlled)
        average_rating: 0,
        total_reviews: 0,
        completed_jobs: 0,

        // earnings
        total_earnings: 0,
        pending_earnings: 0,
        platform_fee_paid: 0,

        status: "new",
      });
    }

    // 4️⃣ Send JWT + cookie
    sendToken(user, res);
  } catch (err) {
    res.status(500).json({
      detail: err.message,
    });
  }
};

// ✅ LOGIN
exports.login = async (req, res) => {
  try {
    const { email, password } = req.body;

    const user = await User.findOne({ email });

    if (!user) {
      return res.status(401).json({
        detail: "Invalid credentials",
      });
    }

    const valid = await bcrypt.compare(password, user.password_hash);

    if (!valid) {
      return res.status(401).json({
        detail: "Invalid credentials",
      });
    }

    sendToken(user, res);
  } catch (err) {
    res.status(500).json({
      detail: err.message,
    });
  }
};

// ✅ LOGOUT
exports.logout = async (req, res) => {
  res.clearCookie("session_token");

  res.json({
    success: true,
    message: "Logged out successfully",
  });
};

// ✅ GET CURRENT USER
exports.getMe = async (req, res) => {
  // req.user is already populated by authMiddleware
  res.json(req.user);
};

// const User = require("../models/User");
// const bcrypt = require("bcryptjs");
// const sendToken = require("../utils/sendToken");
// const jwt = require("jsonwebtoken");

// // ✅ REGISTER
// exports.register = async (req, res) => {
//   try {
//     const { user_id, email, password, name, picture, role, phone, created_at } =
//       req.body;

//     const exists = await User.findOne({ email });

//     if (exists)
//       return res.status(400).json({
//         detail: "Email already registered",
//       });

//     const hash = await bcrypt.hash(password, 10);

//     const user = await User.create({
//       user_id,
//       email,
//       password_hash: hash,
//       name,
//       picture,
//       role,
//       phone,
//       created_at,
//     });

//     sendToken(user, res);
//   } catch (err) {
//     res.status(500).json({
//       detail: err.message,
//     });
//   }
// };

// // ✅ LOGIN
// exports.login = async (req, res) => {
//   try {
//     const { email, password } = req.body;

//     const user = await User.findOne({ email });

//     if (!user)
//       return res.status(401).json({
//         detail: "Invalid credentials",
//       });

//     const valid = await bcrypt.compare(password, user.password_hash);

//     if (!valid)
//       return res.status(401).json({
//         detail: "Invalid credentials",
//       });

//     sendToken(user, res);
//   } catch (err) {
//     res.status(500).json({
//       detail: err.message,
//     });
//   }
// };

// // ✅ LOGOUT
// exports.logout = async (req, res) => {
//   res.clearCookie("session_token");

//   res.json({
//     success: true,
//     message: "Logged out successfully",
//   });
// };

// // ✅ GET CURRENT USER
// exports.getMe = async (req, res) => {
//   res.json(req.user);
// };
